name: Publish package to GitHub Packages

on:
  workflow_dispatch:
  push:
    branches: [ ghpkg ]

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          java-version: '1.8'
          distribution: 'openjdk'
      - name: Publish package
        run: mvn --batch-mode -Ddoclint:none deploy
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
